---
upload_path: "/content/"
frontmatter_file_url_template: "/content/"
body_file_url_template: "/content/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: 0.31.1
